#!/bin/sh

echo "Current dir: $(pwd)"

echo "Start git pre-commit"

.githooks/run-spotless-apply.sh
RESULT=$?
if [ $RESULT -ne 0 ]
then
  exit $RESULT
fi

.githooks/run-gradle-build.sh
RESULT=$?

echo "End git pre-commit"
exit $RESULT
