spring:
  mvc:
    converters:
      preferred-json-mapper: gson
  gson:
    serialize-nulls: true
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://db:3306/dic
    username: dic
    password: dic
  flyway:
    baseline-on-migrate: true
server:
  error:
    include-message: always
  servlet:
    session:
      timeout: 30m
      cookie:
        max-age: 30m
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
