version: "3.9"

services:
  db:
    build:
      context: db
      dockerfile: .
    ports:
      - "3306:3306"
    container_name: dic-mysql
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
  backend:
    build:
      context: backend
      dockerfile: .
    ports:
      - "8080:8080"
      - "5005:5005"
    container_name: dic-backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../../design_in_china_backend:/app/backend
